name: mensurationhealthapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted SDK constraint for compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  provider: ^6.1.5
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  syncfusion_flutter_calendar: ^30.1.42
  animate_do: ^4.2.0
  fl_chart: ^1.0.0
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview_web: ^1.1.2
  flutter_inappwebview: ^6.1.5
  table_calendar: ^3.2.0
  flutter_datetime_picker_plus: ^2.1.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.3
  change_app_package_name: ^1.5.0
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  
  # NEW: Dependencies for downloadable report feature
  path_provider: ^2.1.3 
  permission_handler: ^11.3.1 
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true